service: aws-python-flask-dynamodb-api-project

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  stage: dev
  vpc:
    securityGroupIds:
     - sg-07c1fa76da3d54e8a
    subnetIds:
     - subnet-0a7f4cc40107152ad
  environment:
    DB_URI: mongodb://root12345:root12345@docdb-2022-08-10-18-06-43.cluster-cfqxwcq1eups.us-east-1.docdb.amazonaws.com:27017/?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
    DB_NAME: taxi_aggregator_selector
    USERS_TABLE: user_registration
    TAXI_TABLE: taxi_registration
    AREA_TABLE: area_registration
    TAXI_LOCATION: taxi_location
    USER_TRIP: user_trip
    AUTO_SEQUENCE: auto_sequence

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

