service: aws-capstone-taxi-aggregator-selecter

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  stage: dev
  iam:
    role: arn:aws:iam::292494533295:role/service-role/aws-python-flask-dynamodb-api-project-dev-api-role-w054xqlq
  vpc:
    securityGroupIds:
     - sg-07c1fa76da3d54e8a #plugin will add LambdaExecutionSecurityGroup to this list
    subnetIds:
     - subnet-09e231dae4c8b5c7e # plugin will add the "Application" subnets to this list
  environment:
    DB_URI: mongodb://root1234:root1234@docdb-2022-08-11-05-25-30.cluster-cfqxwcq1eups.us-east-1.docdb.amazonaws.com:27017/?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
    DB_NAME: taxi_aggregator_selector
    USERS_TABLE: user_registration
    TAXI_TABLE: taxi_registration
    AREA_TABLE: area_registration
    TAXI_LOCATION: taxi_location
    USER_TRIP: user_trip
    AUTO_SEQUENCE: auto_sequence

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

